name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
      NEXT_PUBLIC_GCP_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_GCP_PROJECT_ID }}
      NEXT_PUBLIC_GCP_REGION: ${{ secrets.NEXT_PUBLIC_GCP_REGION }}
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service_account.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Prepare GCP credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/service_account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service_account.json" >> $GITHUB_ENV
      
      - name: Enable Firebase Experiments
        run: firebase experiments:enable webframeworks --project=${{ secrets.NEXT_PUBLIC_GCP_PROJECT_ID }}

      - name: Debug Firebase Authentication
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
          cat $GOOGLE_APPLICATION_CREDENTIALS
          firebase projects:list

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project=${{ secrets.NEXT_PUBLIC_GCP_PROJECT_ID }}